# Generated by Django 3.1 on 2021-07-09 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210709_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
